### ISSUE TITLE
LaTeX in README.md not properly typeset

### ISSUE THREAD

**Issue by jergao** [BelugaHaechi/US-International-Scientific-Keyboard#1]
Since [it is possible](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) to use $\LaTeX$ commands enclosed within `$`s, the README should use the more correct way to display $\LaTeX$. This error makes the project unusable. Please fix soon.

**Comment by BelugaHaechi** [comment]
Yep, $\LaTeX$ works. However I didn’t find a way to put it between italicized text, so I changed that paragraph to a quote block :)
