### ISSUE TITLE
Unify naming of the keyboard?

### ISSUE THREAD

**Issue by jergao** [BelugaHaechi/US-International-Scientific-Keyboard#14]
In the README, there are times where the keyboard is referred to as the `US-International and Scientific keyboard` and other times as `US International Scientific keyboard`. Which one is correct?

**Comment by BelugaHaechi** [comment]
It's now unified to `US International Scientific keyboard layout`. There, however, is one instance of `US-International and Scientific keyboard` which is the keyboard description text.
