### ISSUE TITLE
Pilcrow Sign ¶

### ISSUE THREAD

**Issue by jeggao** [BelugaHaechi/US-International-Scientific-Keyboard#16]
**Is your feature request related to a problem? Please describe.**
I see that you have the section symbol `§` in the keyboard. But, as someone who deals with law, I use the pilcrow sign often in my work.

**Describe the solution you'd like**
Add U+00B6 to the keyboard, preferably near `P`.

**Describe alternatives you've considered**
I _need_ the pilcrow man. _Please_ give me the pilcrow sign. **I need it on my keyboard.**
¶I need it.
## _¶I Need It._
# *¶I NEED THE PILCROW SIGN.*

**Additional context**
PLEASE!!!! PLEASE!!!

**Comment by jeggao** [comment]
# THANKS FOR PINNING THIS ISSUE. DOES THAT MEAN YOU WILL ADD OUR LORD AND SAVIOR THE PILCROW `¶`?

**Comment by jeggao** [comment]
# I HAVE NOT HEARD BACK FROM YOU?????

**Comment by BelugaHaechi** [comment]
Finally, Our Holy Lord And Savior the Pilcrow Sign has been added to the keyboard layout! 
U+00B6 is now exactly mapped to key `P` as requested. 
It took a lot of time to figure out the best solution, as the keyboard was already very optimized and getting extra space out of it was unimaginably hard :)

Please check Release v1.5.1 for details.

**Comment by BelugaHaechi** [comment]
¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
