### ISSUE TITLE
Thoughts regarding basing the project on another program?

### ISSUE THREAD

**Issue by jergao** [BelugaHaechi/US-International-Scientific-Keyboard#7]
Since MSKLC development has stagnated for decades, are there plans for re-basing the program on other alive projects? For example, as a [kanata](https://github.com/jtroo/kanata) configuration file?

**Comment by BelugaHaechi** [comment]
It's true that relying on a old, basically unmaintained, non-open source software to do this is not optimal, but it's currently the best and most low-level method to achieve custom keyboard layouts on Windows (which, by the way is itself not open source). I do hope that there is a better way (and I wish Michael Kaplan revives)…

kanata looks like a cool tool, but like many other tools out there, they work as an extra layer/program that runs above the keyboard output, which is not low-level enough.
