### ISSUE TITLE
Artifacts on Keyboard Diagram

### ISSUE THREAD

**Issue by jergao** [BelugaHaechi/US-International-Scientific-Keyboard#8]
Hello. I have noticed that there are artifacts on the keyboard layout diagram. _**Please**_ fix this. It is _unusable_ with the artifacts. Use the browser-integrated screenshot tool if it is from a website. @BelugaHaechi

**Comment by BelugaHaechi** [comment]
qaq

**Comment by BelugaHaechi** [comment]
Thanks for creating a high res version of the keyboard layout overview figure!
